laravel/web/routes/admin.php
<?php

use Illuminate\Http\Request;

//Auth::routes();

Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);

// Registration Routes...
//Route::get('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
//Route::post('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);

// Password Reset Routes...
Route::get('password/forgot', ['as' => 'auth.password.forgot', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'auth.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.reset');
Route::post('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\ResetPasswordController@reset']);

Route::get('password/edit', 'PasswordController@edit')->name('password.edit');
Route::put('password/update', 'PasswordController@update')->name('password.update');

Route::get('/', 'DashboardController@index')->name('dashboard.index');

Route::get('customers/datatable', 'CustomerController@datatable')->name('customers.datatable');
Route::get('customers/distributors', 'CustomerController@distributors')->name('customers.distributors');
Route::resource('customers', 'CustomerController')->except([ 'create', 'edit' ]);

Route::resource('assets', 'AssetController')->except([ 'index', 'show' ]);
Route::get('assets/create/{sector_id?}/{category_id?}', 'AssetController@create')->name('assets.create');
Route::get('assets/browse/{sector_id?}/{category_id?}', 'AssetController@browse')->name('assets.browse');
Route::get('assets/{id}/load-content', 'AssetController@loadContent')->name('assets.loadcontent');

Route::get('assetCategories/datatable', 'AssetCategoryController@datatable')->name('assetcategories.datatable');
Route::resource('assetcategories', 'AssetCategoryController')->except([ 'show' ]);

Route::get('events/datatable', 'EventController@datatable')->name('events.datatable');

Route::resource('events', 'EventController')->only([ 'index', 'show' ]);

Route::get('event-gallery/list', 'EventGalleryController@list')->name('eventgallery.list');
Route::get('event-gallery/detail/{id}', 'EventGalleryController@detail')->name('eventgallery.details');
Route::get('event-gallery/create/{id?}', 'EventGalleryController@create')->name('eventgallery.create');
Route::DELETE('event-gallery/destroy/{id?}', 'EventGalleryController@destroy')->name('eventgallery.destroy');
Route::post('event-gallery/store', 'EventGalleryController@store')->name('eventgallery.store');
Route::get('event-gallery/{id}/edit/', 'EventGalleryController@edit')->name('eventgallery.edit');
Route::put('event-gallery/{id}/update/', 'EventGalleryController@update')->name('eventgallery.update');
Route::resource('event-gallery', 'EventGalleryController')->only([ 'create', 'show' ]);

Route::get('invitations/datatable', 'InvitationController@datatable')->name('invitations.datatable');
Route::resource('invitations', 'InvitationController')->only([ 'index', 'show' ]);

Route::get('pages/datatable', 'PageController@datatable')->name('pages.datatable');
Route::resource('pages', 'PageController')->except([ 'show' ]);

Route::get('sectors/datatable', 'SectorController@datatable')->name('sectors.datatable');
Route::resource('sectors', 'SectorController')->except([ 'show' ]);

Route::get('regions/{id}/change', 'RegionController@change')->name('regions.change');
Route::get('regions/datatable', 'RegionController@datatable')->name('regions.datatable');
Route::resource('regions', 'RegionController')->except([ 'show' ]);

Route::get('events/datatable', 'EventController@datatable')->name('events.datatable');
Route::resource('events', 'EventController')->except([ 'create', 'store', 'edit', 'delete' ]);

Route::get('emailTemplates/datatable', 'EmailTemplateController@datatable')->name('emailtemplates.datatable');
Route::get('emailTemplates/syncFromSendinblue', 'EmailTemplateController@syncFromSendinblue')->name('emailTemplates.syncFromSendinblue');
Route::put('emailTemplates/{id}/activate', 'EmailTemplateController@activate')->name('emailTemplates.activate');
Route::put('emailTemplates/{id}/deactivate', 'EmailTemplateController@deactivate')->name('emailTemplates.deactivate');
Route::resource('emailTemplates', 'EmailTemplateController')->except([ 'create', 'store', 'show', 'destroy' ]);

Route::get('admins/roles', 'AdminController@roles')->name('admins.roles');
Route::get('admins/datatable', 'AdminController@datatable')->name('admins.datatable');
Route::resource('admins', 'AdminController')->except([ 'show' ]);

Route::get('logs', 'LogController@index')->name('logs.index');
Route::get('logs/datatable', 'LogController@datatable')->name('logs.datatable');

Route::get('users/datatable', 'UserController@datatable')->name('users.datatable');
Route::post('users/{id}/approve', 'UserController@approve')->name('users.approve');
Route::resource('users', 'UserController')->except([ 'show' ]);

Route::get('values/datatable', 'ValueController@datatable')->name('values.datatable');
Route::resource('values', 'ValueController')->except([ 'show' ]);

laravel/web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);
Route::get('register/complete', 'Auth\RegisterController@showCompletePage')->name('register.complete');

/*
Route::get('register/form', 'RegisterController@form')->name('register.form');
Route::post('register/submit', 'RegisterController@register')->name('register.submit');

Route::post('auth/login', 'Auth\LoginController@login')->name('auth.login');
Route::post('auth/logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::get('verification/notice', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('verification/resend', 'Auth\VerificationController@resend')->name('verification.resend');
Route::get('verification/verify', 'Auth\VerificationController@verify')->name('verification.verify');
*/

Route::get('lead/{user_code}/form', 'LeadFormController@form')->name('leadform.form');
Route::post('lead/{user_code}/submit', 'LeadFormController@submit')->name('leadform.submit');

Route::get('privacy-policy', 'PageController@privacyPolicy');
Route::get('contact-us', 'PageController@contactUs');

Route::middleware(['verified', 'approved'])->group(function () {

    Route::get('/', 'OnboardController@index')->name('home');

    Route::get('user/profile', 'UserController@profile')->name('user.profile');
    Route::post('user/update-profile', 'UserController@updateProfile')->name('user.update_profile');
    Route::get('user/change-password', 'UserController@changePassword')->name('user.change_password');
    Route::post('user/update-password', 'UserController@updatePassword')->name('user.update_password');

    Route::get('customers/list/{fc?}/{fs?}', 'CustomerController@index')->name('customers');
    Route::get('customers/datatable/{fc?}/{fs?}', 'CustomerController@datatable')->name('customers.datatable');
    Route::get('customers/create', 'CustomerController@create')->name('customers.create');
    Route::post('customers/store', 'CustomerController@store')->name('customers.store');
    Route::get('customers/{id}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::put('customers/{id}/update', 'CustomerController@update')->name('customers.update');
    Route::delete('customers/{id}/destroy', 'CustomerController@destroy')->name('customers.destroy');
    Route::get('customers/import', 'CustomerController@import')->name('customers.import');
    Route::post('customers/uploadExcel', 'CustomerController@uploadExcel')->name('customers.upload_excel');

    Route::get('events', 'EventController@index')->name('events');
    Route::get('events/create', 'EventController@create')->name('events.create');
    Route::post('events/store', 'EventController@store')->name('events.store');
    Route::get('events/{id}/show', 'EventController@show')->name('events.show');
    Route::get('events/{id}/edit', 'EventController@edit')->name('events.edit');
    Route::put('events/{id}/update', 'EventController@update')->name('events.update');
    Route::delete('events/{id}/destroy', 'EventController@destroy')->name('events.destroy');
    Route::get('events/{id}/create-invitation', 'EventController@createInvitation')->name('events.create_invitation');
    Route::get('events/{id}/collect-invitations-stats', 'EventController@collectInvitationsStats')->name('events.collect_invitations_stats');
    Route::get('events/datatable', 'EventController@datatable')->name('events.datatable');

    Route::get('invitations/{id}/template', 'InvitationController@template')->name('invitations.template');
    Route::get('invitations/{id}/choose-template/{template_id}', 'InvitationController@chooseTemplate')->name('invitations.choose_template');
    Route::get('invitations/{id}/customize', 'InvitationController@customize')->name('invitations.customize');
    Route::get('invitations/{id}/confirmation', 'InvitationController@confirmation')->name('invitations.confirmation');
    Route::post('invitations/{id}/test', 'InvitationController@test')->name('invitations.test');

    Route::post('ajax/invitations/{id}/save', 'InvitationController@ajax_save')->name('ajax.invitations.save');
    Route::post('ajax/invitations/{id}/test', 'InvitationController@ajax_test')->name('ajax.invitations.test');
    Route::post('ajax/invitations/{id}/send', 'InvitationController@ajax_send')->name('ajax.invitations.send');

    Route::get('event-assets', 'AssetController@selectSector')->name('assets');
    Route::get('event-assets/{sector_slug?}/{region_id?}/{view?}/{sort?}/{fc?}/{search?}', 'AssetController@browse')->name('assets.browse');

    Route::get('event-gallery/{region_id?}', 'EventGalleryController@selectSector')->name('event-gallery');
    Route::get('event-gallery-detail/{event_id}/{category?}/{view?}/{sort?}/{fc?}/{search?}', 'EventGalleryController@browse')->name('eventgallery.browse');
    Route::post('event-gallery-store/', 'EventGalleryController@store')->name('eventgallery.store');
    Route::post('event-gallery-destroy/', 'EventGalleryController@destroy')->name('eventgallery.destroy');

    Route::get('new-package/deselect-all', 'NewPackageController@deselectAll')->name('new_package.deselect_all');
    Route::get('new-package/compress', 'NewPackageController@compress')->name('new_package.compress');

    Route::get('gallery', 'GalleryController@index')->name('gallery');

    Route::get('ajax/new-package/add-asset/{asset_id}', 'NewPackageController@addAsset')->name('new_package.add_asset');

    Route::get('ajax/new-package/add-gallery/{gallery_id}', 'NewPackageController@addGallery')->name('new_package.add_gallery');
    Route::get('new-package/deselect-all-gallery', 'NewPackageController@deselectAllGallery')->name('new_package.deselect_all_gallery');
    Route::get('new-package/compress-gallery', 'NewPackageController@compressGallery')->name('new_package.compress_gallery');

    Route::get('new-package/upload-gallery', 'NewPackageController@uploadGallery')->name('new_package.upload_gallery');

});

Route::get('hubspot/test/createcontact/{email}/{firstname}/{lastname}', 'HomeController@hubspot_createContact');

laravel/web/resources/views/admin/layouts/footer.blade.php
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<!-- Main Footer -->
		<footer class="main-footer">
			<!-- To the right -->
			<div class="pull-right hidden-xs">
				{{ env('APP_NAME') }}
			</div>
			<!-- Default to the left -->
			<strong>Copyright &copy; 2018 <a href="{{ url('/') }}">{{ env('APP_NAME') }}</a>.</strong> All rights reserved.
		</footer>


	</div>
	<!-- ./wrapper -->

	<!-- REQUIRED JS SCRIPTS -->

	<script src="{{ asset('assets/vendor/jquery/jquery-3.3.1.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/jquery-magnific-popup/jquery.magnific-popup.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/moment/min/moment.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/tinymce/tinymce.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/datatables/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/datatables/dataTables.bootstrap.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/iCheck/icheck.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/select2/select2.min.js') }}"></script>
	<script src="{{ asset('assets/adminlte/js/adminlte.min.js') }}"></script>
	<script src="{{ asset('assets/js/admin.js') }}"></script>

	@stack('scripts')

</body>
</html>

laravel/web/resources/views/admin/layouts/main.blade.php
@include('admin.layouts.header')
@yield('content')
@include('admin.layouts.footer')

laravel/web/resources/views/admin/layouts/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">

            <li class="header">MAIN NAVIGATION</li>

            <li class="{{ \Route::currentRouteName() == 'admin.dashboard.index' ? 'active' : '' }}">
                <a href="{{ route('admin.dashboard.index') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
            </li>

            <li class="{{ \Route::currentRouteName() == 'admin.customers.index' ? 'active' : '' }}">
                <a href="{{ route('admin.customers.index') }}"><i class="fa fa-address-card"></i> <span>Customers</span></a>
            </li>

            <li class="treeview {{ str_is('admin.assets*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-files-o"></i> <span>Assets</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.assets.browse' ? 'active' : '' }}">
                        <a href="{{ route('admin.assets.browse') }}"><i class="fa fa-circle-o"></i> <span>Asset list</span></a>
                    </li>
                    <li class="{{ \Route::currentRouteName() == 'admin.assets.create' ? 'active' : '' }}">
                        <a href="{{ route('admin.assets.create') }}"><i class="fa fa-circle-o"></i> <span>Add asset</span></a>
                    </li>
                    <li class="{{ \Route::currentRouteName() == 'admin.assetategories.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.assetcategories.index') }}"><i class="fa fa-circle-o"></i> <span>Category list</span></a>
                    </li>
                </ul>
            </li>

            <li class="treeview {{ str_is('admin.events*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-calendar"></i> <span>Events</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.events.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.events.index') }}"><i class="fa fa-circle-o"></i> <span>Event list</span></a>
                    </li>
                </ul>
            </li>

            <li class="treeview {{ str_is('admin.eventgallery*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-list"></i> <span>Event Gallery</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.eventgallery.list' ? 'active' : '' }}">
                        <a href="{{ route('admin.eventgallery.list')}}"><i class="fa fa-circle-o"></i> <span>Event Galleries</span></a>
                    </li>
                </ul>
            </li>

            <!--
            <li class="treeview {{ str_is('admin.invitations*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-send"></i> <span>Invitations</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.invitations.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.invitations.index') }}"><i class="fa fa-circle-o"></i> <span>Invitation list</span></a>
                    </li>
                </ul>
            </li>
            -->

            <li class="header">SETTINGS</li>

            @if (\Auth::guard('admin')->user()->role == 'Super Admin')

            <li class="{{ str_is('admin.pages*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="{{ route('admin.pages.index') }}"><i class="fa fa-book"></i> <span>Pages</span></a>
            </li>

            <li class="{{ str_is('admin.sectors*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="{{ route('admin.sectors.index') }}"><i class="fa fa-building-o"></i> <span>Sectors</span></a>
            </li>

            <li class="{{ str_is('admin.regions*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="{{ route('admin.regions.index') }}"><i class="fa fa-globe"></i> <span>Regions</span></a>
            </li>

            <li class="{{ str_is('admin.emailTemplates*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="{{ route('admin.emailTemplates.index') }}"><i class="fa fa-file-text-o"></i> <span>Email templates</span></a>
            </li>

            <li class="treeview {{ str_is('admin.admins*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Admins</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.admins.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.admins.index') }}"><i class="fa fa-circle-o"></i> <span>Admin list</span></a>
                    </li>
                    <!--
                    <li class="{{ \Route::currentRouteName() == 'admin.admins.create' ? 'active' : '' }}">
                        <a href="{{ route('admin.admins.create') }}"><i class="fa fa-circle-o"></i> <span>Create admin</span></a>
                    </li>
                    -->
                    <!--
                    <li class="{{ \Route::currentRouteName() == 'admin.admins.roles' ? 'active' : '' }}">
                        <a href="{{ route('admin.admins.roles') }}"><i class="fa fa-circle-o"></i> <span>Roles</span></a>
                    </li>
                    -->
                    <!--
                    <li class="{{ \Route::currentRouteName() == 'admin.logs' ? 'active' : '' }}">
                        <a href="{{ route('admin.logs.index') }}"><i class="fa fa-circle-o"></i> <span>Logs</span></a>
                    </li>
                    -->
                </ul>
            </li>
            @endif

            <li class="treeview {{ str_is('admin.users*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Distributors</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <?php
                        $region_id = \Session::get('region_id', \Auth::guard('admin')->user()->region_id);
                        $users = App\User::where('region_id', $region_id)->where('approved_at', NULL)->get();
                    ?>
                    <li class="{{ \Route::currentRouteName() == 'admin.users.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.users.index') }}">
                            <i class="fa fa-circle-o"></i> <span>Distributor list</span>
                            @if ($users->count() > 0)
                            <span class="pull-right-container">
                                <small class="label pull-right bg-red">{{ $users->count() }}</small>
                            </span>
                            @endif
                        </a>
                    </li>
                    <li class="{{ \Route::currentRouteName() == 'admin.users.create' ? 'active' : '' }}">
                        <a href="{{ route('admin.users.create') }}"><i class="fa fa-circle-o"></i> <span>Create distributor's access</span></a>
                    </li>
                </ul>
            </li>

            <!--
            <li class="treeview {{ str_is('admin.values*', \Route::currentRouteName()) ? 'active menu-open' : '' }}">
                <a href="#">
                    <i class="fa fa-book"></i> <span>Values</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ \Route::currentRouteName() == 'admin.values.index' ? 'active' : '' }}">
                        <a href="{{ route('admin.values.index') }}"><i class="fa fa-circle-o"></i> <span>Value list</span></a>
                    </li>
                    <li class="{{ \Route::currentRouteName() == 'admin.values.create' ? 'active' : '' }}">
                        <a href="{{ route('admin.values.create') }}"><i class="fa fa-circle-o"></i> <span>Create value</span></a>
                    </li>
                </ul>
            </li>
            -->

        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>